### ISSUE TITLE
Error: Plugin doesn't work with the new backend architecture

### ISSUE THREAD

**Issue by javier-fiore** [CircleCI-Public/backstage-plugin#8]
When we try to use this plugin whit the new backend architecture, we receive a 401 unauthorized when it try to access to circleCI api.

Maybe you must update this repo with the scaffolding created with create-app program to make it work with the new backstage.

**Comment by supersol** [comment]
@javier-fiore 
Maybe this helps. Lots of googling brought me here. I think they just gave up supporting this plugin. I'm using the one from the older repo `@backstage/plugin-circleci` 
And I also had this issue. So I solved it adding
```
    proxy:
      endpoints:
        /circleci/api:
          changeOrigin: true
          headers:
            Circle-Token: ${CIRCLECI_AUTH_TOKEN}
          target: https://circleci.com/api/v1.1
          credentials: dangerously-allow-unauthenticated
```
I have all the setup in local network so for me it's pretty safe. Backstage forced auth internally between plugins. I have no idea where do I need set those internal credentials, so I just allowed access without them.
https://backstage.io/docs/plugins/proxying/
