### ISSUE TITLE
Error: Plugin doesn't support private repositories

### ISSUE THREAD

**Issue by atanass** [CircleCI-Public/backstage-plugin#9]
Hi, this is more of a question - does the plugin support private repositories?
We've had an issue with displaying CircleCI info in Backstage, getting an error when trying to load the page (`Request failed with status code 404`). Requests to the proxy API returns: 
```
{
  "message" : "Project not found"
}
```
What we noticed is that this issue persists only when the repository behind the CircleCI project is set to "private" where other repos with "internal" status are fine with the plugin.
Is there any specific configuration that needs to be in place in order for the plugin to read CircleCI data from private repos?
Here is our config:
```
proxy:
  endpoints:
    '/circleci/api':
      target: https://circleci.com/api/v1.1
      headers:
        Circle-Token: ${CIRCLECI_AUTH_TOKEN}
```

Are these assumptions correct and if yes, is there any work around this so that private repos end up in Backstage?
